#!/bin/bash
cd ${0%/*} || exit 1    # Run from this directory

source "../../src/common/shellFunctions"

chemistry=act
simTime=5
gas=CH4
folder_name=0D_${chemistry}_${gas}
cp -r 0D $folder_name
cd $folder_name

    echo -n "setParameter: "
    ( setParameter gas $gas && setParameter chemistry $chemistry && setParameter simTime $simTime ) > log.setParameter 2>&1 && echo "PASS" || echo "FAIL"

    echo -n "blockMesh: "
    blockMesh > log.blockMesh 2>&1 && echo "PASS" || echo "FAIL"

    echo -n "setICBC: "
    setICBC > log.setICBC 2>&1 && echo "PASS" || echo "FAIL"

    echo -n "foamDictionary: "
    foamDictionary -expand caseDict > log.foamDictionary 2>&1 && echo "PASS" || echo "FAIL"

    echo -n "foamRun: "
    foamRun -solver multiphaseEuler > log.foamRun 2>&1 && echo "PASS" || echo "FAIL"

cd ..
