#!/bin/bash -e

surfaceFeatures | tee log.surfaceFeatures #&& surfaceFeatureConvert constant/triSurface/all.eMesh constant/triSurface/all.obj
blockMesh
decomposePar
NPROCS=$(foamDictionary -entry numberOfSubdomains -value system/decomposeParDict | tail -n 1)
kN=$(foamDictionary -expand -entry kN -value caseParamsDict | tail -n 1)
mpirun -np $NPROCS snappyHexMesh -parallel -overwrite | tee log.snappyHexMesh
reconstructPar
rm -r processor*
# topoSet | tee log.topoSet0
checkMesh -allTopology | tee log.checkMesh

# createPatch -overwrite
renumberMesh -overwrite
topoSet -dict "system/topoSetDict_kN${kN}" | tee log.topoSet

N_CV_SL=$(sed -n 's/.*cellSet controlVolume_SL now size \([0-9]\+\)/\1/p' log.topoSet | head -n 1)
N_CV_DC=$(sed -n 's/.*cellSet controlVolume_DC now size \([0-9]\+\)/\1/p' log.topoSet | head -n 1)
N_CV_AR=$(sed -n 's/.*cellSet controlVolume_AR now size \([0-9]\+\)/\1/p' log.topoSet | head -n 1)
N_CV_FR=$(sed -n 's/.*cellSet controlVolume_FR now size \([0-9]\+\)/\1/p' log.topoSet | head -n 1)
N_CV_tot=$((N_CV_SL+N_CV_DC+N_CV_AR+N_CV_FR))
N_cells=$(sed -n 's/.*cells: *\([0-9]\+\)/\1/p' log.checkMesh)

# N_outlet_AR=$(sed -n 's/.*faceSet outlet_AR now size \([0-9]\+\)/\1/p' log.topoSet | head -n 1)
# N_outlet_FR=$(sed -n 's/.*faceSet outlet_FR now size \([0-9]\+\)/\1/p' log.topoSet | head -n 1)
N_FS_SL_AR=$(sed -n 's/.*faceSet controlSurface_SL_AR now size \([0-9]\+\)/\1/p' log.topoSet | head -n 1)
N_FS_SL_FR=$(sed -n 's/.*faceSet controlSurface_SL_FR now size \([0-9]\+\)/\1/p' log.topoSet | head -n 1)
N_FS_DC_AR=$(sed -n 's/.*faceSet controlSurface_DC_AR now size \([0-9]\+\)/\1/p' log.topoSet | head -n 1)
N_FS_DC_FR=$(sed -n 's/.*faceSet controlSurface_DC_FR now size \([0-9]\+\)/\1/p' log.topoSet | head -n 1)

# inlet AR = 22x15
# inlet FR = 11x15
# if [ "$N_outlet_AR" -ne "$((26*13))" ]; then
#   echo "WARNING! Number of faces in outlet_AR patch $N_outlet_AR is not correct $((26*13))"
#   sleep 5
# fi
# if [ "$N_outlet_FR" -ne "$((15*13))" ]; then
#   echo "WARNING! Number of faces in outlet_FR patch $N_outlet_FR is not correct $((15*13))"
#   sleep 5
# fi
if [ "$N_FS_SL_AR" -ne "$((29*120))" ]; then
  echo "WARNING! Number of faces in SL_AR control surface $N_FS_SL_AR is not correct $((29*120))"
  sleep 5
fi
if [ "$N_FS_SL_FR" -ne "$((22*120))" ]; then
  echo "WARNING! Number of faces in SL_FR control surface $N_FS_SL_FR is not correct $((22*120))"
  sleep 5
fi
if [ "$N_FS_DC_AR" -ne "$((10*7))" ]; then
  echo "WARNING! Number of faces in DC_AR control surface $N_FS_DC_AR is not correct $((10*7))"
  sleep 5
fi
if [ "$N_FS_DC_FR" -ne "$((38*7))" ]; then
  echo "WARNING! Number of faces in DC_FR control surface $N_FS_DC_FR is not correct $((38*7))"
  sleep 5
fi

N_cells_diff=$((N_CV_tot-N_cells))
if [ "$N_cells_diff" -ne 0 ]; then
  echo "WARNING! Number of cells is different."
  echo "checkMesh:      $N_cells" 
  echo "controlVolumes: $N_CV_tot" 
  sleep 5
fi

# decomposePar
# mpirun -np 36 foamRun -solver multiphaseEuler > log 2>&1 &