#!/bin/bash

source "../../src/common/shellFunctions"

prepareCase () {
    chemistry=$1
    gas=$2
    simTime=$3
    solidsMass=$4
    T=$5
    CASE_NAME=labReactor_${chemistry}_${gas}_${solidsMass}g_${T}C
    TK=$(bc <<< "scale=4; $T+273.15")
    if [ ! -d "$CASE_NAME" ]; then
        cp -r labReactor $CASE_NAME
    else
        echo "$CASE_NAME already exists"
    fi
    if [ $gas == "H2" ]; then
        defaultSpecie=H2O
    elif [ $gas == "CO" ]; then
        defaultSpecie=CO2
    fi
    echo "./runCase $CASE_NAME --chemistry $chemistry --gas $gas "\
         " --defaultSpecie $defaultSpecie --simTime $simTime "\
         " --solidsMass 0.00$solidsMass --T $TK --nVolRate_mLn_min 900"\
         "  >/dev/null 2>&1 &"
}

# NOTE THAT AFTER THE CORRECTION of fitted temperature THE HEAT RELEASE CHANGED!
#      T     before   after
# CH4  950     80.9   133.7    -> temperature reduction will be larger  (+40%?)
# CO   950   - 60.8  - 47.6    -> temperature increase  will be smaller (-22%?)
# H2   950   - 28.1  - 14.9    -> temperature increase  will be smaller (-47%?)
# O2   950   -441.9  -468.3    -> temperature increase  will be larger  (+ 6%?)

prepareCase act H2 30 3 800  # Original temperature at the inlet
prepareCase act H2 30 3 850  # Additional
prepareCase act H2 25 3 900  # Additional
prepareCase act H2 25 3 950  # Additional
prepareCase act H2 25 3 1000 # Additional
prepareCase act H2 20 3 1050 # Original temperature at the inlet
prepareCase act H2 40 6 900  # Extra case with 6 g
prepareCase act H2 40 6 950  # Extra case with 6 g
prepareCase act H2 30 6 1000 # Extra case with 6 g

# Original temperatures at the inlet
prepareCase act CO 110 3 800  # Original temperature at the inlet
prepareCase act CO 90  3 850  # Additional
prepareCase act CO 60  3 900  # Original temperature at the inlet
prepareCase act CO 50  3 950  # Original temperature at the inlet
prepareCase act CO 40  3 1000 # Original temperature at the inlet
prepareCase act CO 35  3 1050 # Original temperature at the inlet
prepareCase act CO 80  6 900  # Extra case with 6 g
prepareCase act CO 70  6 950  # Extra case with 6 g
prepareCase act CO 90  6 1000 # Extra case with 6 g

# 18 cases