#!/bin/bash
cd ${0%/*} || exit 1    # Run from this directory

source "../../src/common/shellFunctions"

chemistry=act
gas=CH4
simTime=0.00025
folder_name=labReactor_test

rm -rf "$folder_name"
cp -r labReactor "$folder_name"
cd "$folder_name"

    echo -n "setParameter: "
    ( setParameter gas "$gas" \
        && setParameter chemistry "$chemistry" \
        && setParameter simTime "$simTime" \
    ) > log.setParameter 2>&1 && echo "PASS" || echo "FAIL"

    echo -n "PrepareMesh: "
    ./PrepareMesh > log.PrepareMesh 2>&1 && echo "PASS" || echo "FAIL"

    echo -n "setICBC: "
    setICBC > log.setICBC 2>&1 && echo "PASS" || echo "FAIL"

    echo -n "setFields: "
    setFields > log.setFields 2>&1 && echo "PASS" || echo "FAIL"

    echo -n "foamDictionary: "
    foamDictionary -expand caseDict > log.foamDictionary 2>&1 && echo "PASS" || echo "FAIL"

    echo -n "foamRun: "
    foamRun -solver multiphaseEuler > log.foamRun 2>&1 && echo "PASS" || echo "FAIL"

cd ..
